site_name: Teaterbanken
site_url: https://bjorkan.github.io/Teaterbanken/
theme:
  name: material
  language: sv
  features:
    - search.suggest
  palette:
    primary: pink
  icon:
    logo: fontawesome/solid/masks-theater
